"""Structured financial research report templates."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Mapping, Sequence


_LABELS = {
    "zh-CN": {
        "meta": "报告信息",
        "type": "报告类型",
        "rating": "评级",
        "summary": "核心结论",
        "facts": "事实与证据",
        "assumptions": "关键假设",
        "metrics": "关键指标",
        "metric": "指标",
        "value": "数值",
        "risks": "风险提示",
        "citations": "引用来源",
        "next_steps": "下一步",
        "no_citations": "未提供外部引用；请在正式发布前补充数据来源。",
        "disclaimer": "免责声明：本报告由 AI 投研系统生成，仅供研究参考，不构成投资建议。",
    },
    "en": {
        "meta": "Report Metadata",
        "type": "Report Type",
        "rating": "Rating",
        "summary": "Executive Summary",
        "facts": "Facts and Evidence",
        "assumptions": "Key Assumptions",
        "metrics": "Key Metrics",
        "metric": "Metric",
        "value": "Value",
        "risks": "Risk Disclosure",
        "citations": "Citations",
        "next_steps": "Next Steps",
        "no_citations": "No external citations were provided; add sources before formal publication.",
        "disclaimer": "Disclaimer: This report is generated by an AI research system for research reference only and does not constitute investment advice.",
    },
}


def _labels(language: str) -> Mapping[str, str]:
    return _LABELS["zh-CN"] if language.lower() in {"zh", "zh-cn", "cn"} else _LABELS["en"]


def _clean_items(items: Sequence[str]) -> list[str]:
    return [str(item).strip() for item in items if str(item).strip()]


@dataclass(frozen=True)
class ResearchReportTemplate:
    """Professional, auditable Markdown template for investment research."""

    title: str
    report_type: str
    rating: str
    summary: Sequence[str]
    facts: Sequence[str]
    assumptions: Sequence[str]
    metrics: Mapping[str, object] = field(default_factory=dict)
    risks: Sequence[str] = field(default_factory=list)
    citations: Sequence[str] = field(default_factory=list)
    next_steps: Sequence[str] = field(default_factory=list)
    language: str = "en"

    def render_markdown(self) -> str:
        """Render the report as structured Markdown.

        Raises:
            ValueError: If risk disclosure is missing.
        """
        risk_items = _clean_items(self.risks)
        if not risk_items:
            raise ValueError("risk disclosure is required")

        labels = _labels(self.language)
        title = self.title.strip() or "Research Report"
        lines: list[str] = [
            f"# {title}",
            "",
            f"## {labels['meta']}",
            f"- **{labels['type']}**: {self.report_type.strip() or 'research'}",
            f"- **{labels['rating']}**: {self.rating.strip() or 'Unrated'}",
            "",
        ]
        lines.extend(self._section(labels["summary"], _clean_items(self.summary)))
        lines.extend(self._section(labels["facts"], _clean_items(self.facts)))
        lines.extend(self._section(labels["assumptions"], _clean_items(self.assumptions)))
        lines.extend(self._metrics_section(labels))
        lines.extend(self._section(labels["risks"], risk_items))
        citation_items = _clean_items(self.citations) or [labels["no_citations"]]
        lines.extend(self._section(labels["citations"], citation_items))
        lines.extend(self._section(labels["next_steps"], _clean_items(self.next_steps)))
        lines.extend(["", labels["disclaimer"]])
        return "\n".join(lines).strip() + "\n"

    @staticmethod
    def _section(title: str, items: list[str]) -> list[str]:
        lines = [f"## {title}"]
        if not items:
            lines.append("- Not provided.")
        else:
            lines.extend(f"- {item}" for item in items)
        lines.append("")
        return lines

    def _metrics_section(self, labels: Mapping[str, str]) -> list[str]:
        lines = [
            f"## {labels['metrics']}",
            f"| {labels['metric']} | {labels['value']} |",
            "|---|---|",
        ]
        if not self.metrics:
            lines.append("| Not provided | - |")
        else:
            for key, value in self.metrics.items():
                lines.append(f"| {key} | {value} |")
        lines.append("")
        return lines
